# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnings_are_errors: false
r: bioc-release
r_github_packages:
  - zdk123/SpiecEasi
before_install:
  - sudo apt-get install gsl-bin libgsl0-dev
