#' @importFrom vegan capscale
#' @importFrom vegan envfit
#' @importFrom vegan vegdist
#' @importFrom vegan estimateR
#' @importFrom vegan diversity
#' @importFrom vegan specnumber
#' @importFrom vegan eigenvals
#' @importFrom vegan betadisper
#' @importFrom vegan ordiellipse
#' @importFrom vegan adonis
#' @importFrom stats TukeyHSD
#' @importFrom stats cov
#' @importFrom stats p.adjust
#' @importFrom stats wilcox.test
#' @importFrom stats na.omit
#' @importFrom stats median
#' @importFrom stats sd
#' @importFrom stats quantile
#' @importFrom stats rnorm
#' @importFrom stats cor
#' @importFrom stats pnorm
#' @importFrom stats cor.test
#' @importFrom stats pchisq
#' @importFrom stats AIC
#' @importFrom stats BIC
#' @importFrom stats logLik
#' @importFrom utils write.table
#' @importFrom dirmult dirmult
#' @importFrom phyloseq tax_table
#' @importFrom phyloseq otu_table
#' @importFrom phyloseq sample_data
#' @importFrom phyloseq taxa_names
#' @importFrom phyloseq phyloseq
#' @importFrom phyloseq plot_network
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 geom_boxplot
#' @importFrom ggplot2 ggtitle
#' @importFrom ggplot2 geom_jitter
#' @importFrom ggplot2 position_jitter
#' @importFrom ggplot2 aes
#' @importFrom ggpubr stat_compare_means
#' @importFrom reshape2 melt
#' @importFrom SpiecEasi spiec.easi
#' @importFrom SpiecEasi adj2igraph
#' @importFrom SpiecEasi symBeta
#' @importFrom SpiecEasi getOptBeta
#' @importFrom igraph degree
#' @importFrom igraph graph_from_edgelist
#' @importFrom igraph V
#' @importFrom igraph V<-
#' @importFrom igraph E
#' @importFrom igraph E<-
#' @importFrom igraph ends
#' @importFrom igraph delete.vertices
#' @importFrom igraph graph_from_adjacency_matrix
#' @importFrom igraph as_adj
#' @importFrom cluster pam
#' @importFrom clusterCrit bestCriterion
#' @importFrom clusterCrit intCriteria
#' @importFrom bnlearn hpc
#' @importFrom bnlearn si.hiton.pc
#' @importFrom bnlearn fast.iamb
#' @importFrom bnlearn gs
#' @importFrom bnlearn iamb.fdr
#' @importFrom bnlearn mmpc
#' @importFrom bnlearn pc.stable
#' @importFrom bnlearn hc
#' @importFrom bnlearn tabu
#' @importFrom bnlearn mmhc
#' @importFrom bnlearn rsmax2
#' @importFrom bnlearn h2pc
#' @importFrom bnlearn aracne
#' @importFrom bnlearn boot.strength
#' @importFrom bnlearn bn.fit
#' @importFrom DirichletMultinomial mixture
#' @importFrom DirichletMultinomial dmn
#' @importFrom DirichletMultinomial goodnessOfFit
#' @importFrom graphics par
#' @importFrom graphics plot
#' @importFrom graphics arrows
#' @importFrom graphics text
#' @importFrom graphics legend
#' @importFrom graphics barplot
#' @importFrom graphics boxplot
#' @importFrom graphics points
#' @importFrom graphics hist
#' @importFrom graphics mtext
#' @importFrom graphics abline
#' @importFrom grDevices rgb
#' @importFrom grDevices hsv
#'
.onAttach <- function(lib, pkg)
{
  packageStartupMessage('\nseqgroup: Analysis of Sequencing Data with Groups')
}
